### ISSUE TITLE
Invalid WebSocket frame: RSV2 and RSV3 must be clear

### ISSUE THREAD

**Issue by bughp** [parse-community/ParseLiveQuery-Android#104]
hmy_server      | /home/node/app/node_modules/parse-server/lib/ParseServer.js:218
hmy_server      |           throw err;
hmy_server      |           ^
hmy_server      | 
hmy_server      | RangeError: Invalid WebSocket frame: RSV2 and RSV3 must be clear
hmy_server      |     at Receiver.getInfo (/home/node/app/node_modules/parse-server/node_modules/ws/lib/receiver.js:160:14)
hmy_server      |     at Receiver.startLoop (/home/node/app/node_modules/parse-server/node_modules/ws/lib/receiver.js:121:22)
hmy_server      |     at Receiver._write (/home/node/app/node_modules/parse-server/node_modules/ws/lib/receiver.js:69:10)
hmy_server      |     at doWrite (_stream_writable.js:415:12)
hmy_server      |     at writeOrBuffer (_stream_writable.js:399:5)
hmy_server      |     at Receiver.Writable.write (_stream_writable.js:299:11)
hmy_server      |     at Socket.socketOnData (/home/node/app/node_modules/parse-server/node_modules/ws/lib/websocket.js:788:35)
hmy_server      |     at Socket.emit (events.js:193:13)
hmy_server      |     at Socket.EventEmitter.emit (domain.js:481:20)
hmy_server      |     at addChunk (_stream_readable.js:295:12)
hmy_server      | npm ERR! code ELIFECYCLE
hmy_server      | npm ERR! errno 7
hmy_server      | npm ERR! parse-server-dashboard@1.0.0 start: ` node index.js`
hmy_server      | npm ERR! Exit status 7
hmy_server      | npm ERR! 
hmy_server      | npm ERR! Failed at the parse-server-dashboard@1.0.0 start script.
hmy_server      | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
hmy_server      | 
hmy_server      | npm ERR! A complete log of this run can be found in:
hmy_server      | npm ERR!     /root/.npm/_logs/2019-05-06T03_22_00_491Z-debug.log

**Comment by bughp** [comment]
compile 'com.parse:parse-android:1.17.3'
    compile 'com.parse:parse-livequery-android:1.0.5'

**Comment by ozbillwang** [comment]
@bughp 

Did you fix this issue? I got the same error.

**Comment by mmimeault** [comment]
Hello,

this seem to be an error on the backend side? Maybe you should ask at https://github.com/parse-community/parse-server.
