### ISSUE TITLE
Live queries stop working at some point

### ISSUE THREAD

**Issue by qmetzler-luna** [parse-community/ParseLiveQuery-Android#43]
Hi,

Not sure where to look to fix the issue (Parse server or this library) we are having an error and the live queries stop to work after that.
Here is the crashlog : 

> studio.lunabee.whoomies.debug E/ParseLiveQueryClient: Socket onError
                                                                                   javax.net.ssl.SSLException: Read error: ssl=0x75f4e600: I/O error during system call, Connection timed out
                                                                                       at com.android.org.conscrypt.NativeCrypto.SSL_read(Native Method)
                                                                                       at com.android.org.conscrypt.OpenSSLSocketImpl$SSLInputStream.read(OpenSSLSocketImpl.java:689)
                                                                                       at okio.Okio$2.read(Okio.java:138)
                                                                                       at okio.AsyncTimeout$2.read(AsyncTimeout.java:236)
                                                                                       at okio.RealBufferedSource.request(RealBufferedSource.java:66)
                                                                                       at okio.RealBufferedSource.require(RealBufferedSource.java:59)
                                                                                       at okio.RealBufferedSource.readByte(RealBufferedSource.java:72)
                                                                                       at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:113)
                                                                                       at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:97)
                                                                                       at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:262)
                                                                                       at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:201)
                                                                                       at okhttp3.RealCall$AsyncCall.execute(RealCall.java:135)
                                                                                       at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                       at java.lang.Thread.run(Thread.java:841)

Do you know where to look to solve this issue?

Thanks.

**Comment by qmetzler-luna** [comment]
Or on another device I can have the following with the same consequences.

> 04-18 17:03:30.022 4701-4774/studio.lunabee.whoomies.debug E/ParseLiveQueryClient: Socket onError
                                                                                   java.io.EOFException
                                                                                       at okio.RealBufferedSource.require(RealBufferedSource.java:59)
                                                                                       at okio.RealBufferedSource.readByte(RealBufferedSource.java:72)
                                                                                       at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:113)
                                                                                       at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:97)
                                                                                       at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:262)
                                                                                       at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:201)
                                                                                       at okhttp3.RealCall$AsyncCall.execute(RealCall.java:135)
                                                                                       at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                       at java.lang.Thread.run(Thread.java:818)

**Comment by mmimeault** [comment]
Hello,

Could you provide more infos...

- You are saying it "stop working at some point", it works for how much time?
- Did you try it without SSL? (to see if the problem is only SSL related)
- Does the app crash? (asking that because you said crashlog)
- Do you see any logs on the parse server side?

Thanks.

**Comment by qmetzler-luna** [comment]
Hello,

The app is not crashing I should have said error logs.
Mobile devices are connecting to the server through https and the cloud code is called using http (without that we had red error logs telling us that the cloud code cannot connect to the parse API).
When we start the server, queries made from mobile devices and cloud function calls are working well. But about 1 or 2 days after, the cloud functions and the live query server are not responding (the queries made from the mobile devices are still working).
On the server side, we can see in the logs a lot of "[object Object]" and we are sure this logs aren't generated by us.
We can't see any cloud function calls logs anymore.
We have other servers working well, the only difference is that they don't implement any live query servers.

Thanks.

**Comment by mmimeault** [comment]
Hello,

It's not the client that stop working at some point but the server, right?
Maybe you should reopen your issue on parse-server instead.

Thanks

**Comment by qmetzler-luna** [comment]
Hi,

Yes, sorry the only "issue" on the Android side was that it's not reconnecting after that. I managed it in the error listener.
We reposted the issue in the parse-server repo.

Thanks.
