### ISSUE TITLE
ParseLiveQueryClient: Socket onError

### ISSUE THREAD

**Issue by Rasalexman** [parse-community/ParseLiveQuery-Android#45]
Hi, i use parse live query with back4app server and i get this error.
i simple use:
parseLiveQueryClient = ParseLiveQueryClient.Factory.getClient();
subscriptionHandling = parseLiveQueryClient.subscribe(askQuery);

java.net.ProtocolException: Expected HTTP 101 response but was '401 Unauthorized'
                                                                            at okhttp3.internal.ws.RealWebSocket.checkResponse(RealWebSocket.java:216)
                                                                            at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:183)
                                                                            at okhttp3.RealCall$AsyncCall.execute(RealCall.java:135)
                                                                            at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
                                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
                                                                            at java.lang.Thread.run(Thread.java:856)

please help

**Comment by mmimeault** [comment]
Did you setup parse first?
You need to initialize Parse SDK first. With the proper serverUrl, clientKey, applicationId.
```
        Parse.Configuration build = new Parse.Configuration.Builder(this)
                .applicationId(applicationId)
                .clientKey(clientKey)
                .server(serverUrl)
                .build();
```

**Comment by mmimeault** [comment]
If yes, is your live query server listen on the same URL? same port?

**Comment by Rasalexman** [comment]
i resolve my problem, sorry for spend your time. please close this issue. 
Update:
needed to set ParseLiveQueryClient.Factory.getClient(new URI("wss://my_parse_back4app_io.com"));

**Comment by mmimeault** [comment]
Ok thanks
