### ISSUE TITLE
Expected HTTP 101 response but was '403 Forbidden'

### ISSUE THREAD

**Issue by sharity-app** [parse-community/ParseLiveQuery-Android#66]
Major error the library. seems Client key is not passed...

E/ParseLiveQueryClient: Socket onError
                                                                               java.net.ProtocolException: Expected HTTP 101 response but was '403 Forbidden'
                                                                                   at okhttp3.internal.ws.RealWebSocket.checkResponse(RealWebSocket.java:216)
                                                                                   at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:183)
                                                                                   at okhttp3.RealCall$AsyncCall.execute(RealCall.java:141)
                                                                                   at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                                                                                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                                   at java.lang.Thread.run(Thread.java:776)

**Comment by sadok90** [comment]
hi 'm having the same issue any help

**Comment by mmimeault** [comment]
Can you guys provide more information about your environement setup? 
-Parse server (&live query) version
-http our https
-snippet of code that show how you are using the live query client.

This livequery client is currently used in production, so it works. Maybe something has changed on the server code / or a wrong configuration.

**Comment by maravilhosinga** [comment]
Same problem here
