### ISSUE TITLE
SSLHandshakeException: Connection closed by peer

### ISSUE THREAD

**Issue by drojokef** [parse-community/ParseLiveQuery-Android#67]
Hi,
When I try to run the app, logcat give me this err:

```
Socket onError
                                                         javax.net.ssl.SSLHandshakeException: Connection closed by peer
                                                             at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
                                                             at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:357)
                                                             at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:267)
                                                             at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:237)
                                                             at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:148)
                                                             at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:186)
                                                             at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:121)
                                                             at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:100)
                                                             at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
                                                             at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                             at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                             at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
                                                             at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)

```

I have internet permission.
My inits:

```
 Parse.initialize(...................);
   try {
            ParseLiveQueryClient parseLiveQueryClient = ParseLiveQueryClient.Factory.getClient(new URI("wss://192.168.1.2:1337"));
            parseLiveQueryClient.connectIfNeeded();
        } catch (URISyntaxException e) {
            e.printStackTrace();
        }
```

**Comment by hermanliang** [comment]
Seems your parse server didn't have SSL certification.
You may try one of the following initialize configurations

Let LiveQuery config the websocket URI refer from parse server URL (recommended)
```java
ParseLiveQueryClient parseLiveQueryClient = ParseLiveQueryClient.Factory.getClient();
```
or 
```java
ParseLiveQueryClient parseLiveQueryClient = ParseLiveQueryClient.Factory.getClient(new URI("ws://192.168.1.2:1337"));
```

**Comment by drojokef** [comment]
Yes, it works. My stupid mistake. Problem was : URI("wss...")   to change  URI("ws...")  
Thank you hermanliang.

**Comment by drojokef** [comment]
After change URI("wss...") to change URI("ws..."), worked well, but after couple of minutes I got this err even any changes :

```
 java.lang.InstantiationError: okhttp3.internal.ws.RealWebSocket
                                                              at okhttp3.OkHttpClient.newWebSocket(OkHttpClient.java:414)
                                                              at com.parse.OkHttp3SocketClientFactory$OkHttp3WebSocketClient.open(OkHttp3SocketClientFactory.java:90)
                                                              at com.parse.ParseLiveQueryClientImpl.reconnect(ParseLiveQueryClientImpl.java:157)
                                                              at com.parse.ParseLiveQueryClientImpl.connectIfNeeded(ParseLiveQueryClientImpl.java:115)
                                                              at com.test.MainApp.onCreate(MainApp.java:31)
```
  The cause of error :  `parseLiveQueryClient.connectIfNeeded();`

**Comment by SHASHANKREDDY316** [comment]
When I m trying to login in chess. Com application I could find as connection to peer may I know what might be the problem and how could I resolve?

**Comment by mtrezza** [comment]
@SHASHANKREDDY316 For help with Parse Platform we recommend our [community forum](https://community.parseplatform.org) or our [community chat](https://chat.parseplatform.org). This issue is closed.
