### ISSUE TITLE
ParseLiveQueryClient: Socket onError

### ISSUE THREAD

**Issue by bluetoothfx** [parse-community/ParseLiveQuery-Android#69]
Situation: I am working on Latest parse server (2.5.3) which is deployed locally. I can connect and save & retrieve my objects from parse server. Now when I am trying to implement the live query I am getting error. On the line when I am trying to get the client.

    public static final URI WS_URL = URI.create("ws://10.0.2.2:1337/parse/"); // As calling from emulator
    **ParseLiveQueryClient parseLiveQueryClient = ParseLiveQueryClient.Factory.getClient(WS_URL);** // generating error on this line   
 
And I implemented my event like this way:
ParseQuery<ParseObject> parseQuery = ParseQuery.getQuery("GameScore");
        SubscriptionHandling<ParseObject> subscriptionHandling = parseLiveQueryClient.subscribe(parseQuery);

        subscriptionHandling.handleEvents(new SubscriptionHandling.HandleEventsCallback<ParseObject>() {
            @Override
            public void onEvents(ParseQuery<ParseObject> query, SubscriptionHandling.Event event, ParseObject object) {
                // HANDLING all events
                ParseQuery<ParseObject> mm = query;
            }
        });

java.io.IOException: unexpected end of stream on Connection{10.0.2.2:1337, proxy=DIRECT@ hostAddress=/10.0.2.2:1337 cipherSuite=none protocol=http/1.1}
at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:205)
                                                           at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:75)
                                                           at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                           at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
                                                           at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                           at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                           at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
                                                           at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                           at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                           at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
                                                           at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                           at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
                                                           at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                           at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                           at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
                                                           at okhttp3.RealCall$AsyncCall.execute(RealCall.java:135)
                                                           at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                                                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                           at java.lang.Thread.run(Thread.java:818)
                                                        Caused by: java.io.EOFException: \n not found: limit=0 content=…
                                                           at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:227)
                                                           at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:211)
                                                           at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)
                                                           at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:75) 
                                                           at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) 
                                                           at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45) 
                                                           at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) 
                                                           at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) 
                                                           at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93) 
                                                           at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) 
                                                           at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) 
                                                           at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) 
                                                           at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) 
                                                           at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120) 
                                                           at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) 
                                                           at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) 
                                                           at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185) 
                                                           at okhttp3.RealCall$AsyncCall.execute(RealCall.java:135) 
                                                           at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) 
                                                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                           at java.lang.Thread.run(Thread.java:818)

**Comment by Kastr** [comment]
I'm having the same problem.
@bluetoothfx did you manage to solve it?

**Comment by Kastr** [comment]
Solved it. Instead of running the server using parse-server, I used npm start.

**Comment by bluetoothfx** [comment]
Solved it using two different port number. Didn't remember perfectly but my starting sequence were may be like below..>>
parse server
npm install
npm start
